name: Build and Publish Docker Image
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
      
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'
        
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: 0xm4r71n/libraryapp:latest
        
    - name: Push image digest to file
      id: digest
      run: echo ${{ steps.build.outputs.digest }} > image_digest
      
    - name: Upload image digest artifact
      uses: actions/upload-artifact@v2
      with:
        name: image_digest
        path: image_digest
